name = "bacselect-download-counter"
main = "src/worker.js"
compatibility_date = "2026-08-31"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://bacselect.github.io,http://127.0.0.1:8766,http://localhost:8766"

[[d1_databases]]
binding = "DB"
database_name = "bacselect-download-counter"
database_id = "fe2f1f03-0b97-4aed-bfac-64d4d4360195"
